# Generated by Django 3.1.2 on 2020-10-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20201021_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Coding Hacks', 'Coding Hacks'), ('Sports', 'Sports'), ('Finance', 'Finance'), ('Current Events', 'Current Events'), ('Cooking', 'Cooking'), ('Lifestyle Hacks', 'Lifestyle Hacks'), ('Entertainment', 'Entertainment'), ('Neutral', 'Neutral'), ('Fitness', 'Fitness')], default='Neutral', max_length=250),
        ),
    ]
