# Generated by Django 3.1.2 on 2020-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
